import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  title = 'practise';
  is3d = true;
  circuitId = '1234-23456-234234-234234234-234234-HSJ12';

  nodes = [{
    id:1,
    name:'Equipment',
    type:'point',
    neName:'1-AJSDKJAJSDD-ASDASD-ASAD',
    TID:'BADFSD-FDFSD-234234-REW',
    CLLI:'CLLI-100032223',
    neType:'Fiber Mux',
    vendor:'CISCO',
    model:'KLJ',
    shelf0:1,
    shelf1:1,
    slot0:2,
    slot1:2,
    subSlot0:'--',
    subSlot1:'--',
    port0:'C01',
    port1:'C01'
  },{
    id:2,
    name:'Equipment 2',
    type:'equipment',
    neName:'2-AJSDKJAJSDD-ASDASD-ASAD',
    TID:'BADFSD-FDFSD-234234-REW',
    CLLI:'CLLI-100032223',
    neType:'Fiber Mux',
    vendor:'CISCO',
    model:'KLJ',
    shelf0:1,
    shelf1:1,
    slot0:2,
    slot1:2,
    subSlot0:'--',
    subSlot1:'--',
    port0:'C01',
    port1:'C01'
  },{
    id:3,
    name:'Equipment 3',
    type:'equipment',
    neName:'3-AJSDKJAJSDD-ASDASD-ASAD',
    TID:'BADFSD-FDFSD-234234-REW',
    CLLI:'CLLI-100032223',
    neType:'Fiber Mux',
    vendor:'CISCO',
    model:'KLJ',
    shelf0:1,
    shelf1:1,
    slot0:2,
    slot1:2,
    subSlot0:'--',
    subSlot1:'--',
    port0:'C01',
    port1:'C01'
  },{
    id:4,
    name:'Equipment 4',
    type:'equipment',
    neName:'4-AJSDKJAJSDD-ASDASD-ASAD',
    TID:'BADFSD-FDFSD-234234-REW',
    CLLI:'CLLI-100032223',
    neType:'Fiber Mux',
    vendor:'CISCO',
    model:'KLJ',
    shelf0:1,
    shelf1:1,
    slot0:2,
    slot1:2,
    subSlot0:'--',
    subSlot1:'--',
    port0:'C01',
    port1:'C01'
  },{
    id:5,
    name:'Equipment 5',
    type:'equipment',
    neName:'5-AJSDKJAJSDD-ASDASD-ASAD',
    TID:'BADFSD-FDFSD-234234-REW',
    CLLI:'CLLI-100032223',
    neType:'Fiber Mux',
    vendor:'CISCO',
    model:'KLJ',
    shelf0:1,
    shelf1:1,
    slot0:2,
    slot1:2,
    subSlot0:'--',
    subSlot1:'--',
    port0:'C01',
    port1:'C01'
  },
  {
    id:5,
    name:'Equipment 6',
    type:'equipment',
    neName:'5-AJSDKJAJSDD-ASDASD-ASAD',
    TID:'BADFSD-FDFSD-234234-REW',
    CLLI:'CLLI-100032223',
    neType:'Fiber Mux',
    vendor:'CISCO',
    model:'KLJ',
    shelf0:1,
    shelf1:1,
    slot0:2,
    slot1:2,
    subSlot0:'--',
    subSlot1:'--',
    port0:'C01',
    port1:'C01'
  },
  {
    id:5,
    name:'Equipment 7',
    type:'equipment',
    neName:'5-AJSDKJAJSDD-ASDASD-ASAD',
    TID:'BADFSD-FDFSD-234234-REW',
    CLLI:'CLLI-100032223',
    neType:'Fiber Mux',
    vendor:'CISCO',
    model:'KLJ',
    shelf0:1,
    shelf1:1,
    slot0:2,
    slot1:2,
    subSlot0:'--',
    subSlot1:'--',
    port0:'C01',
    port1:'C01'
  },
  {
    id:5,
    name:'Equipment 8',
    type:'equipment',
    neName:'5-AJSDKJAJSDD-ASDASD-ASAD',
    TID:'BADFSD-FDFSD-234234-REW',
    CLLI:'CLLI-100032223',
    neType:'Fiber Mux',
    vendor:'CISCO',
    model:'KLJ',
    shelf0:1,
    shelf1:1,
    slot0:2,
    slot1:2,
    subSlot0:'--',
    subSlot1:'--',
    port0:'C01',
    port1:'C01'
  },
  {
    id:5,
    name:'Equipment 9',
    type:'equipment',
    neName:'5-AJSDKJAJSDD-ASDASD-ASAD',
    TID:'BADFSD-FDFSD-234234-REW',
    CLLI:'CLLI-100032223',
    neType:'Fiber Mux',
    vendor:'CISCO',
    model:'KLJ',
    shelf0:1,
    shelf1:1,
    slot0:2,
    slot1:2,
    subSlot0:'--',
    subSlot1:'--',
    port0:'C01',
    port1:'C01'
  },
  {
    id:5,
    name:'Equipment 10',
    type:'equipment',
    neName:'5-AJSDKJAJSDD-ASDASD-ASAD',
    TID:'BADFSD-FDFSD-234234-REW',
    CLLI:'CLLI-100032223',
    neType:'Fiber Mux',
    vendor:'CISCO',
    model:'KLJ',
    shelf0:1,
    shelf1:1,
    slot0:2,
    slot1:2,
    subSlot0:'--',
    subSlot1:'--',
    port0:'C01',
    port1:'C01'
  }
]

links = [
  
  {
    sourceLocation:'Equipment',
    targetLocation:'Equipment 2',
    linetype:'Circuit',
    circuitName:'1-AJSDKJAJSDD-ASDASD-ASAD',
    display:'Yes',
    type:'EBH',
    serviceType:'PTP',
    status:'IN_SERVICE',
    bandwidth:'10 GBPS'
  },
  {
    sourceLocation:'Equipment 2',
    targetLocation:'Equipment 3',
    linetype:'Patch',
    display:'No'
  },
  {
    sourceLocation:'Equipment 3',
    targetLocation:'Equipment 4',
    linetype:'Segment',
    segmentName:'1-AJSDKJAJSDD-ASDASD-ASAD',
    display:'Yes',
    type:'EBH',
    serviceType:'PTP',
    status:'IN_SERVICE',
    bandwidth:'200 GBPS'
  },
  {
    sourceLocation:'Equipment 3',
    targetLocation:'Equipment 5',
    cableName:'1-AJSDKJAJSDD-ASDASD-ASAD',
    linetype:'Cable',
    display:'Yes',
    type:'EBH',
    length:'12',
    status:'IN_SERVICE',
  },
  {
    sourceLocation:'Equipment 5',
    targetLocation:'Equipment 6',
    cableName:'1-AJSDKJAJSDD-ASDASD-ASAD',
    linetype:'Cable',
    display:'Yes',
    type:'EBH',
    length:'12',
    status:'IN_SERVICE',
  },
  {
    sourceLocation:'Equipment 4',
    targetLocation:'Equipment 6',
    linetype:'Circuit',
    circuitName:'1-AJSDKJAJSDD-ASDASD-ASAD',
    display:'Yes',
    type:'EBH',
    serviceType:'PTP',
    status:'IN_SERVICE',
    bandwidth:'10 GBPS'
  },
  {
    sourceLocation:'Equipment 6',
    targetLocation:'Equipment 7',
    linetype:'Patch',
    display:'No'
  },
  {
    sourceLocation:'Equipment 7',
    targetLocation:'Equipment 8',
    linetype:'Segment',
    segmentName:'1-AJSDKJAJSDD-ASDASD-ASAD',
    display:'Yes',
    type:'EBH',
    serviceType:'PTP',
    status:'IN_SERVICE',
    bandwidth:'200 GBPS'
  },
  {
    sourceLocation:'Equipment 7',
    targetLocation:'Equipment 9',
    cableName:'1-AJSDKJAJSDD-ASDASD-ASAD',
    linetype:'Cable',
    display:'Yes',
    type:'EBH',
    length:'12',
    status:'IN_SERVICE',
  },
  {
    sourceLocation:'Equipment 7',
    targetLocation:'Equipment 10',
    cableName:'1-AJSDKJAJSDD-ASDASD-ASAD',
    linetype:'Cable',
    display:'Yes',
    type:'EBH',
    length:'12',
    status:'IN_SERVICE',
  }
];

}

